		#to be worked on later
		jso.write("\t{ \"address\": \"")
		jso.write(dataList[i][2])
		jso.write("\", ")
		jso.write("\"latitude\": \"")
		jso.write(str(location.latitude))
		jso.write("\", \"longitude\": \"")
		jso.write(str(location.longitude))
		jso.write("\", \"index\": \"")
		jso.write(str(i))
		jso.write("\", \"repeats\": \"")
		jso.write(str(repeats))
		jso.write("\", \"additionalInfo\": \"")
		jso.write(additionalInfo)
		jso.write("\"},\n")
